name: Build CyberBot WPF


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Match your version

      - name: Navigate to CyberBot1 folder
        run: cd CyberBot1

      - name: Restore dependencies
        run: dotnet restore CyberBot1/CyberBot1.sln

      - name: Build the solution
        run: dotnet build CyberBot1/CyberBot1.sln --configuration Release

      - name: Publish build (optional)
        run: dotnet publish CyberBot1/CyberBot1.sln --configuration Release --output build
